### ISSUE TITLE
Rayleigh–Bénard convection DataSet

### ISSUE THREAD

**Issue by reyhashemi** [Rose-STL-Lab/Equivariant-Net#2]
I could not find the [Rayleigh–Bénard convection DataSet](https://drive.google.com/drive/folders/1VOtLjfAkCWJePiacoDxC-nrgCREKvrpE?usp=sharing.). Is there a new repository from which I could retrieve this data set?
Thank you in advance.

**Comment by emonhossainraihan** [comment]
@reyhashemi Did you manage the data?

**Comment by reyhashemi** [comment]
Ah, yes thank you! there is a zip file now !
